"""baseline

Revision ID: 45ade04a53cc
Revises:
Create Date: 2026-08-05 18:31:38.948119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ade04a53cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('prompt_hash', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parse_quality', sa.Float(), nullable=False),
    sa.Column('used_ocr', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('family_key', sa.String(length=255), nullable=False),
    sa.Column('regulatory_context', sa.JSON(), nullable=True),
    sa.Column('parsed_document', sa.JSON(), nullable=True),
    sa.Column('funnel', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_family_key'), 'documents', ['family_key'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('configured_as', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_index(op.f('ix_integrations_type'), 'integrations', ['type'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('section_fingerprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_key', sa.String(length=255), nullable=False),
    sa.Column('section_label', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('heading', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_fingerprints_content_hash'), 'section_fingerprints', ['content_hash'], unique=False)
    op.create_index(op.f('ix_section_fingerprints_family_key'), 'section_fingerprints', ['family_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('watch_hits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_hits_source_id'), 'watch_hits', ['source_id'], unique=False)
    op.create_table('watch_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_paragraph_ref', sa.String(length=64), nullable=True),
    sa.Column('functional_area', sa.String(length=32), nullable=False),
    sa.Column('modification_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('deadline_hint', sa.String(length=255), nullable=True),
    sa.Column('linked_prior_obligation_id', sa.String(length=32), nullable=True),
    sa.Column('scores_reference', sa.String(length=255), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_document_id'), 'obligations', ['document_id'], unique=False)
    op.create_index(op.f('ix_obligations_functional_area'), 'obligations', ['functional_area'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_table('evidence_requirements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('obligation_id', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=False),
    sa.Column('required_content', sa.Text(), nullable=False),
    sa.Column('collector', sa.String(length=128), nullable=False),
    sa.Column('retention_period', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('upload_target', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('external_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_requirements_obligation_id'), 'evidence_requirements', ['obligation_id'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('obligation_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('filing_type', sa.String(length=128), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_obligation_id'), 'filings', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_filings_status'), 'filings', ['status'], unique=False)
    op.create_table('obligation_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligation_comments_obligation_id'), 'obligation_comments', ['obligation_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('obligation_id', sa.String(length=32), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('evaluation_criterion', sa.Text(), nullable=False),
    sa.Column('timeline', sa.String(length=255), nullable=True),
    sa.Column('threshold_value', sa.String(length=255), nullable=True),
    sa.Column('is_qualitative', sa.Boolean(), nullable=False),
    sa.Column('evidence_type', sa.String(length=255), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_obligation_id'), 'rules', ['obligation_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('obligation_id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('functional_area', sa.String(length=32), nullable=False),
    sa.Column('primary_owner', sa.String(length=128), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('workflow_template', sa.String(length=128), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('depends_on_task_id', sa.String(length=32), nullable=True),
    sa.Column('jira_issue_key', sa.String(length=64), nullable=True),
    sa.Column('docusign_envelope_id', sa.String(length=64), nullable=True),
    sa.Column('overdue_notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_functional_area'), 'tasks', ['functional_area'], unique=False)
    op.create_index(op.f('ix_tasks_obligation_id'), 'tasks', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_obligation_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_functional_area'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_rules_obligation_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_obligation_comments_obligation_id'), table_name='obligation_comments')
    op.drop_table('obligation_comments')
    op.drop_index(op.f('ix_filings_status'), table_name='filings')
    op.drop_index(op.f('ix_filings_obligation_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_evidence_requirements_obligation_id'), table_name='evidence_requirements')
    op.drop_table('evidence_requirements')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_functional_area'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_document_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_table('watch_sources')
    op.drop_index(op.f('ix_watch_hits_source_id'), table_name='watch_hits')
    op.drop_table('watch_hits')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_section_fingerprints_family_key'), table_name='section_fingerprints')
    op.drop_index(op.f('ix_section_fingerprints_content_hash'), table_name='section_fingerprints')
    op.drop_table('section_fingerprints')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_integrations_type'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_family_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
